[book]
authors = ["Alex Casso"]
language = "en"
multilingual = false
src = "src"
title = "EEEN1XXX2 Programming: Notes Part 2"

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "dark"
smart-punctuation = true
mathjax-support = false
copy-fonts = true
no-section-label = true
git-repository-url = "https://github.com/UOM-EEE-EEEN1XXX2/notes-part2"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/UOM-EEE-EEEN1XXX2/notes-part2/edit/master/guide/{path}"
site-url = "/book/"
cname = "myproject.rs"
input-404 = "not-found.md"

[output.html.print]
enable = true    # include support for printable output
page-break = true

[output.html.fold]
enable = false    # whether or not to enable section folding
level = 0

[output.html.playground]
editable = true         # allows editing the source code
copyable = true          # include the copy button for copying code snippets
copy-js = true           # includes the JavaScript for the code editor
line-numbers = true     # displays line numbers for editable code
runnable = true

[output.html.search]
enable = true            # enables the search feature
limit-results = 30       # maximum number of search results
teaser-word-count = 30   # number of words used for a search result teaser
use-boolean-and = true   # multiple search terms must all match
boost-title = 2          # ranking boost factor for matches in headers
boost-hierarchy = 1      # ranking boost factor for matches in page names
boost-paragraph = 1      # ranking boost factor for matches in text
expand = true            # partial words will match longer terms
heading-split-level = 3  # link results to heading levels
copy-js = true

[rust]
edition = "2021"